---
- hosts: all
  gather_facts: true
  become: yes
  roles:
    - { role: containerd }
    - { role: kubernetes }

- hosts:
    - master_main
    - master_backup
  gather_facts: true
  become: yes
  vars:
    k8s_api_address: 192.168.1.9
  roles:
    - { role: masters }

- hosts: workers
  gather_facts: true
  become: yes
  vars:
    k8s_api_address: 192.168.1.9
  roles:
    - { role: workers }
