---
- hosts: all
  gather_facts: true
  become: yes
  roles:
    - { role: containerd }
    - { role: kubernetes }

- hosts:
    - control_plane
  gather_facts: true
  become: yes
  vars:
    k8s_api_address: 192.168.1.9
  roles:
    - { role: control_plane }

- hosts: workers
  gather_facts: true
  become: yes
  vars:
    k8s_api_address: 192.168.1.9
  roles:
    - { role: workers }
