all:
  vars:
    ansible_ssh_user: bpfer
  children:
    control_plane:
      hosts:
        192.168.1.10:
          control_master: True
        192.168.1.11:
          control_master: False
        192.168.1.12:
          control_master: False
    workers:
      hosts:
        192.168.1.20:
        192.168.1.21:
        192.168.1.22:
