all:
  vars:
    ansible_ssh_user: bpfer
  children:
    master_main:
      hosts:
        192.168.1.10:
    master_backup:
      hosts:
        192.168.1.11:
        192.168.1.12:
    workers:
      hosts:
        192.168.1.20:
        192.168.1.21:
        192.168.1.22:
