---
- name: Create Directories for HA Configs and Manifests.
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/haproxy
    - /etc/keepalived
    - /etc/kubernetes/manifests

- name: Copy HAProxy and KeepAliveD Config Templates.
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 777
  loop:
    - { src: haproxy.cfg.j2, dest: /etc/haproxy/haproxy.cfg }
    - { src: check_apiserver.sh.j2, dest: /etc/keepalived/check_apiserver.sh }
    - { src: keepalived.conf.j2, dest: /etc/keepalived/keepalived.conf }

- name: Copy HAProxy and KeepAliveD Manifests.
  copy:
    src: "{{ item }}"
    dest: "/etc/kubernetes/manifests/{{ item }}"
    mode: 777
  loop:
    - haproxy.yaml
    - keepalived.yaml
