---
- name: Install required packages.
  apt:
    state: present
    update_cache: yes
    pkg:
      - jq
      - cifs-utils
      - nfs-common

- name: Create Plugin Directory
  file:
    path: "{{ cifs_plugin_dir }}"
    state: directory

- name: Get CIFS plugin.
  get_url:
    url: https://raw.githubusercontent.com/fstab/cifs/master/cifs
    mode: 0755
    dest: "{{ cifs_plugin_dir }}/cifs"

- name: Join Cluster.
  shell: >
    "{{ worker_join_command | trim }}"
