---
- name: Initialize Kubernetes control plane with kubeadm init
  command: "kubeadm init --pod-network-cidr 172.18.0.0/16 --control-plane-endpoint {{ k8s_api_address }}:8443 --upload-certs"
  register: kubeadmin_init

- name: Print the init output to screen.
  debug:
    var: kubeadmin_init.stdout

- name: Get control plane backup join command.
  set_fact:
    backup_join_command: >
      "{{ kubeadmin_init.stdout | regex_search(regexp, multiline=True) | regex_replace('|\t|\\|\n', '') }}"
  vars:
    regexp: "{{ backup_join_re }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['all'] }}"

- name: Get worker join command.
  set_fact:
    worker_join_command: >
      "{{ kubeadmin_init.stdout | regex_search(regexp, multiline=True) | regex_replace('\t|\\|\n', '') }}"
  vars:
    regexp: "{{ worker_join_re }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['all'] }}"

- name: Print Join Commands.
  debug:
    var: "{{ item }}"
  loop:
    - backup_join_command
    - worker_join_command

- name: Ensure .kube directory exists.
  file:
    path: ~/.kube
    state: directory
    mode: 0755

- name: Symlink the kubectl admin.conf to ~/.kube/conf.
  file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link
    mode: 0644

- name: Add Tigera operator for Calico networking.
  command: "kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/tigera-operator.yaml"
  register: calico_result
  changed_when: "'created' in calico_result.stdout"
  retries: 3
  delay: 5

- name: Copy Calico configuration.
  copy:
    src: calico.yml
    dest: /root/calico.yml
    mode: 0644

- name: Apply Calico configuration.
  command: kubectl create -f /root/calico.yml
  retries: 3
  delay: 5
